# Generated by Django 5.1.4 on 2024-12-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='highschool_transcript',
            field=models.FileField(blank=True, null=True, upload_to='highschool_transcripts/'),
        ),
        migrations.AddField(
            model_name='player',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to='passports/'),
        ),
        migrations.AddField(
            model_name='player',
            name='sat_results',
            field=models.FileField(blank=True, null=True, upload_to='sat_results/'),
        ),
        migrations.AddField(
            model_name='player',
            name='soccer_video',
            field=models.FileField(blank=True, null=True, upload_to='soccer_videos/'),
        ),
        migrations.AddField(
            model_name='player',
            name='toefl_duolingo_results',
            field=models.FileField(blank=True, null=True, upload_to='toefl_duolingo_results/'),
        ),
    ]
